os: linux
language: cpp
dist: bionic
addons:
  apt:
    update: true
    packages:
    - build-essential
    - cmake
    - zlib1g-dev
    - libairspy-dev
    - libusb-1.0-0-dev
before_install:
 - chmod +x .travis-ci/install.sh
 - chmod +x .travis-ci/build.sh
install: .travis-ci/install.sh
script: .travis-ci/build.sh
